name: Factorio tests

on:
  push:
    branches:
    - master
  pull_request_target:
    branches:
    - master

permissions:
  contents: read

jobs:
  test-push:
    if: ${{ github.event_name == 'push' }} 
    uses: pyanodon/pyanodontests/.github/workflows/pytest.yml@v1
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref }}
    secrets:
      token: ${{ secrets.TESTUSER_TOKEN }}
  test-pull-request:
    if: ${{ github.event_name == 'pull_request_target' }} 
    uses: pyanodon/pyanodontests/.github/workflows/pytest.yml@v1
    with:
      repository: ${{ github.repository }}
      ref: refs/pull/${{ github.event.pull_request.number }}/merge
    secrets:
      token: ${{ secrets.TESTUSER_TOKEN }}
